//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class PublicSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PublicSettings defaultInstance = ((PublicSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PublicSettings())));
        
        public static PublicSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StatsBotConnectionString {
            get {
                return ((string)(this["StatsBotConnectionString"]));
            }
            set {
                this["StatsBotConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StatsBotAppHarborString {
            get {
                return ((string)(this["StatsBotAppHarborString"]));
            }
            set {
                this["StatsBotAppHarborString"] = value;
            }
        }
    }
}
